# Use an official ubuntu as a parent image
# build:
#   docker build . -t fastplaz
# enter bash:
#   docker run -it fastplaz bash

FROM luri/free-pascal:multiarch AS base

#VOLUME ["/projects/vendors", "/public_html", "/app"]
RUN mkdir -p /projects/vendors/
WORKDIR /projects
ADD ./app/ /app

# Environment
ENV NAME FastPlaz
ENV DEBIAN_FRONTEND noninteractive

#RUN apt-get update

# ---- Dependencies ----
#FROM base AS dependencies

# Prepare FastPlaz
RUN /app/fastplaz-init.sh

# Prepare Echo Project (example)
ADD ./project-examples/echo /projects/echo/
RUN ln -fs /projects/echo/public_html /var/www/html/echo
RUN chmod -R 777 /projects/echo/public_html/ztemp

# Build Echo Project (example)
RUN cd /projects/echo/source/echo/ && \
  ./build.sh

# run apache
# CMD ["/app/run.sh"]


